/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.6/samples
 */

 plugins {
    `java`
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-lang3:3.0")
}

fun printProjectFiles(project: Project) {
    println("project_path|${project.getPath()}|${project.buildFile}")
}

printProjectFiles(rootProject)
rootProject.subprojects.forEach { sub -> printProjectFiles(sub) }